name: EasyCrypt CI

on:
  workflow_dispatch:
  push:
  pull_request:

env:
  OPAMROOT: /home/charlie/.opam
  OPAMCONFIRMLEVEL: unsafe-yes

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/easycrypt/ec-test-box:r2026.03
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: detect SMT solvers
        run: opam exec -- easycrypt why3config

      - name: test deps
        run: opam exec -- easycrypt runtest tests.config deps

      - name: test proof
        run: opam exec -- easycrypt runtest tests.config proof
